version: 2 # use CircleCI 2.0

references:
  ts_env: &ts_env
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/varbrad.dev
  restore_node_modules: &restore_node_modules
    restore_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

jobs: # a collection of steps
  setup: # runs not using Workflows must have a `build` job as entry point
    <<: *ts_env
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - *restore_node_modules
      - run:
          name: install
          command: yarn
      - *save_node_modules
  lint:
    <<: *ts_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: lint
          command: yarn lint
  test:
    <<: *ts_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: test
          command: yarn test
  build:
    <<: *ts_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: build
          command: yarn build
workflows:
  version: 2
  ts_ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - lint
            - test
