version: 2 # use CircleCI 2.0

references:
  js_env: &js_env
    docker:
      - image: circleci/node:8.15.0
    working_directory: ~/varbrad.dev
  restore_node_modules: &restore_node_modules
    restore_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

jobs: # a collection of steps
  setup: # runs not using Workflows must have a `build` job as entry point
    <<: *js_env
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - *restore_node_modules
      - run:
          name: js:install
          command: yarn
      - *save_node_modules
  js:lint:
    <<: *js_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: js:lint
          command: yarn js:lint
  js:test:
    <<: *js_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: js:test
          command: yarn js:test
  scss:lint:
    <<: *js_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: scss:lint
          command: yarn scss:lint
  build:
    <<: *js_env
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: js:build
          command: yarn build
workflows:
  version: 2
  js_ci:
    jobs:
      - setup
      - js:lint:
          requires:
            - setup
      - js:test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - js:lint
            - js:test