version: 2.1 # use CircleCI 2.0

executors:
  js_env:
    docker:
      - image: circleci/node:8.15.0

jobs: # a collection of steps
  setup: # runs not using Workflows must have a `build` job as entry point
    executor: js_env
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: js:install
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  lint:
    executor: js_env
    steps:
      - run: # run linting
          name: js:lint
          command: yarn lint
  test:
    docker:
      - image: circleci/node:8.15.0
    steps:
      - run:
          name: js:test
          command: yarn test
workflows:
  version: 2.1
  js_ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
